version: '3.7'

services:
    php:
        build:
            context: ./
        volumes:
            - .:/var/www/html
        ports:
            - "80:80"
            - "443:443"
        networks:
          - app-network
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: "A9c@16h-"
        MYSQL_DATABASE: "financeira"
      ports:
        - "3306:3306"
      volumes:
        - db:/var/lib/mysql
      networks:
        - app-network
networks:
  app-network:
    driver: bridge

volumes:
  db:
